### ISSUE TITLE
Creating a database

### ISSUE THREAD

**Issue by katasuno** [roydejong/timbot#18]
Do you have a chance to create a separate database for each guild? For example, a channel added to one guild should not be shared in another. I was able to connect the channel system to the database with the command, but I could not create the twitch channels.

**Comment by roydejong** [comment]
I'm not 100% sure I understand your question, but right now the bot only supports sending stream notifications to all the servers it is in, not a per-server configuration.

If v2 ever gets finished, then this will be possible, but not right now basically. :)
