### ISSUE TITLE
[discord] could not send announce msg

### ISSUE THREAD

**Issue by mohammedgha** [roydejong/timbot#19]
when i try to run the bot it give me this in cmd 
![image_2020-12-06_013809](https://user-images.githubusercontent.com/73617725/101267654-b1d8d680-3763-11eb-9cae-6a92eddcc16a.png)

**Comment by roydejong** [comment]
Thanks, looks like this is a bug for usernames that have spaces in ("cd project red")

**Comment by mohammedgha** [comment]
Yahh i figure this out and now when I removed the channel it works, but i got another problem when i add the role in config.json it keep tell me there's an error and the bot won't run. 

Thanks for your help :D

**Comment by roydejong** [comment]
The latest commit should fix the problem for channels with spaces, give it a try.

If the role thing is still a problem for you, please open a separate issue for it.
