### ISSUE TITLE
RangeError: MessageEmbed field values may not be empty

### ISSUE THREAD

**Issue by sdhjhk** [roydejong/timbot#21]
i installed the bot with your tutorial and everytime it want to post a streaming message, this happens in console:
![sa0JqIg](https://user-images.githubusercontent.com/76795941/103386321-8517a500-4afe-11eb-8d13-df12502d3def.png)

**Comment by roydejong** [comment]
The error message suggests that some field in the live embed is empty when it shouldn't be. Could be a stream with an empty title, possibly. Are you still experiencing this / do you happen to know why this may have happened for this particular stream notification?
