### ISSUE TITLE
I don´t know where is the oauth token

### ISSUE THREAD

**Issue by scuffitotw** [roydejong/timbot#32]
Hello, im using your repo but idk where is the oauth token, i enter in this page https://twitchtokengenerator.com/ but i dont find the oauth token.

**Comment by roydejong** [comment]
Hi. 

You can use https://twitchtokengenerator.com/ to **generate** the tokens, follow these steps:
 1. Go to the website
 2. Click "Custom Scope Token"
 3. Scroll to the bottom, and click the green "Generate Token!" button, then "Authorize" on Twitch
 4. You will now return to the website, complete a captcha, and see the token appear

You will need to copy the **ACCESS TOKEN** and **CLIENT ID** and use both of them in your Timbot config.
