### ISSUE TITLE
Invalid login names, emails or IDs in request

### ISSUE THREAD

**Issue by MayhemBill** [roydejong/timbot#34]
Trying to setup the bot, used both the recommended way to get an oauth token and tokengen website

no matter what I do, it returns with `Invalid login names, emails or IDs in request` 

any idea as to whats going on? I have confirmed that both items are correct in the config.json file.

**Comment by MayhemBill** [comment]
I'm an idiot, ignore this.

**Comment by nosut** [comment]
I am getting the same error. Not sure what I am doing wrong. I have limited it now to only 3 twitch users that I know for sure work but no luck.

**Comment by roydejong** [comment]
If you're getting this error there is most likely an issue with how you've defined the users.

This is basically Twitch saying "I don't understand what you mean".

Could you share how you've configured users, @nosut?

**Comment by roydejong** [comment]
@nosut Could you try defining the names under `twitch_channels` without spaces in between - so just comma seperated? I think that might be the issue

**Comment by nosut** [comment]
> @nosut Could you try defining the names under `twitch_channels` without spaces in between - so just comma seperated? I think that might be the issue

I tried just that and it worked. 
Got a different error though "Field.flat"
 Updated node.js and it's now working however.

Thanks!
