### ISSUE TITLE
[Suggestion] Embedding Stream Profile Pic, adding time since start

### ISSUE THREAD

**Issue by Khaztaroth** [roydejong/timbot#7]
I've found a dirty solution to embed a streamer's profile picture without having to use the API
It's very simple and it only requires one extra file, for this example I'll call it "profileURL"

in profileURL.js we write a module export, add one per streamer you check for

```node
module.exports {
<username in lowercase> : '<URL>',
}
```
The URL can be gotten from this icon on the "about" page in the user's profile, just right click it and select "copy image URL"

![image](https://user-images.githubusercontent.com/10103152/87263782-2c8b1780-c48c-11ea-97e2-9c88c48ef79b.png)

then in our live-embed file, we add a new variable and modify the thumbnail by writing

```node
var pURL = require(./profileURL);

...

msgEmbed.setThumbnail(pURL[streamData.user_name.toLowerCase()])

```

This will break if the streamer changes their profile picture, which is solved by just updating the URL in the "profileURL" file.

Adding time since start requires "momentjs",  to install run `npm install moments`
and then in the live-embed file write a new variable that takes the stream start time and converts it to relative time and use it for a new field.

```node
const moment = require('moment');

class LiveEmbed {
...
const mdate = moment(streamData.started_at).fromNow();
...
if (isLive) {
...
msgEmbed.addField("Started", `About ${mdate}`, true);
}
```

Which returns 

![image](https://user-images.githubusercontent.com/10103152/87264329-b7204680-c48d-11ea-9bc1-35a0ebc6b4ac.png)

You can also modify the output on another variable to remove the "ago" and use it to have the stream's total runtime in the offline message.

**Comment by roydejong** [comment]
I've added stream duration (0fc6191731207ca0207b39b040636fbf2e3f5a66) and tweaked the layout embed a bit, but I've opted for a duration rather than a "time since" for now:

![image](https://user-images.githubusercontent.com/6772638/88467562-80f4b500-ced8-11ea-8ea8-471d7542df04.png)

**Comment by Khaztaroth** [comment]
Wonderful, I was trying to figure out how to have the time uptime be more precise, thank you.

**Comment by roydejong** [comment]
I've added support for user profile pictures in the live embed (adc5df666b2d84839b66bd3938fae8fbc693b9ca).

This solution (re)fetches monitored user profiles every 10 minutes, so it won't require any additional configuration.

![image](https://user-images.githubusercontent.com/6772638/88468232-c61ce500-cee0-11ea-94ba-706d128cfd3c.png)

I'll close the ticket for now as I think this addresses your suggestions.

**Comment by Khaztaroth** [comment]
Thank you so much!
