### ISSUE TITLE
Stream announcements are delayed by a few minutes

### ISSUE THREAD

**Issue by roydejong** [roydejong/timbot#8]
Stream announcements are always delayed by a few minutes compared to Nadekobot's announcements.

Observed for the test bot that I'm running myself. I've compared source code and there is no fundamental difference in polling method or frequency as far as I can tell.

Typical difference appears to be about 1 - 4 minutes, Timbot is always slower without exception.

Thoughts:
- Could be caching on Twitch API side?
- Could be geo difference - Nadeko + streamer is US, Timbot is EU.
- Is there a webhook solution to eliminate delay altogether?

**Comment by SugarD-x** [comment]
A popular moderation bot that has this ability called "MEE6" has the same issue, so I don't think it is just your bot. From what I read in a competing bot's repository, (which is no longer maintained), the interval for checking the Twitch API could not be set below 60 seconds, else it would spam the API and cause issues on Twitch's end. (I'm assuming this means being banned from the API for abuse). Not sure if this helps, but thought I'd mention it.

By the way, I just found your bot and I love the work you've put into it!

**Comment by roydejong** [comment]
Thanks. As you say, lower intervals don't seem to be very useful because the Twitch API seems to give out stale / cached data anyway, plus yeah you'd hit rate limits eventually.

I don't think there's much that can be done here on the bot's end, so I'll close this issue for now.
